function contourScale(art,gap){const box=art.contour?.mmBox||[0,0,art.w,art.h],longest=Math.max(box[2],box[3]);if(longest<=90&&gap<=4)return 2;if(longest<=160)return 1.5;return 1}

function makeMask(art,gap,angle=0,scale=1){const [bx,by,bw,bh]=art.contour.box,physical=art.contour.mmBox||[0,0,art.w,art.h],baseW=Math.max(1,Math.ceil(physical[2]*scale)),baseH=Math.max(1,Math.ceil(physical[3]*scale)),canvas=new OffscreenCanvas(baseW,baseH),ctx=canvas.getContext('2d');ctx.scale(baseW/bw,baseH/bh);ctx.translate(-bx,-by);ctx.fill(new Path2D(art.contour.d));const data=ctx.getImageData(0,0,baseW,baseH).data,source=[];for(let y=0;y<baseH;y++)for(let x=0;x<baseW;x++)if(data[(y*baseW+x)*4+3]>20)source.push([x+.5,y+.5]);if(!source.length)return null;const radians=angle*Math.PI/180,c=Math.cos(radians),s=Math.sin(radians),cx=baseW/2,cy=baseH/2,turned=[],pdfPoints=[];for(const[x,y]of source){turned.push([(x-cx)*c+(y-cy)*s,-(x-cx)*s+(y-cy)*c]);const px=physical[0]+x/baseW*physical[2],py=physical[1]+(baseH-y)/baseH*physical[3];pdfPoints.push([px*c-py*s,px*s+py*c])}const xs=turned.map(point=>point[0]),ys=turned.map(point=>point[1]),minX=Math.floor(Math.min(...xs)),minY=Math.floor(Math.min(...ys)),maxX=Math.ceil(Math.max(...xs)),maxY=Math.ceil(Math.max(...ys)),rawW=Math.max(1,maxX-minX),rawH=Math.max(1,maxY-minY),r=Math.max(0,Math.ceil(gap*scale/2)),w=rawW+r*2,h=rawH+r*2,map=new Uint8Array(w*h);for(const[pX,pY]of turned){const x=Math.floor(pX-minX)+r,y=Math.floor(pY-minY)+r;for(let dy=-r;dy<=r;dy++)for(let dx=-r;dx<=r;dx++)if(dx*dx+dy*dy<=r*r&&x+dx>=0&&x+dx<w&&y+dy>=0&&y+dy<h)map[(y+dy)*w+x+dx]=1}const pixels=[];for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(map[y*w+x])pixels.push([x,y]);return{w,h,pixels,angle,actualW:rawW/scale,actualH:rawH/scale,pad:r/scale,pdfMinX:Math.min(...pdfPoints.map(point=>point[0])),pdfMinY:Math.min(...pdfPoints.map(point=>point[1]))}}

function contourMasks(art,gap,allowRotation,scale){const cache=new Map(),get=angle=>{const normalized=(angle+360)%360;if(!cache.has(normalized))cache.set(normalized,makeMask(art,gap,normalized,scale));return cache.get(normalized)},coarse=allowRotation?Array.from({length:24},(_,index)=>index*15):[0],coarseMasks=coarse.map(get).filter(Boolean);if(!allowRotation)return coarseMasks;const promising=[...coarseMasks].sort((a,b)=>a.w*a.h-b.w*b.h).slice(0,8),angles=new Set([0,90,180,270]);for(const mask of promising)for(const delta of[-5,-2,-1,0,1,2,5])angles.add((mask.angle+delta+360)%360);const ranked=[...angles].map(get).filter(Boolean).sort((a,b)=>a.w*a.h-b.w*b.h),zero=get(0);return[zero,...ranked.filter(mask=>mask.angle!==0).slice(0,7)]}

function maskFits(board,boardW,mask,x,y){for(const[px,py]of mask.pixels)if(board[(y+py)*boardW+x+px])return false;return true}

function maskContact(board,boardW,boardH,mask,x,y){let contact=0,step=Math.max(1,Math.floor(mask.pixels.length/240));for(let i=0;i<mask.pixels.length;i+=step){const[px,py]=mask.pixels[i],bx=x+px,by=y+py;if(bx===0||by===0||bx===boardW-1||by===boardH-1||board[by*boardW+Math.max(0,bx-1)]||board[by*boardW+Math.min(boardW-1,bx+1)]||board[Math.max(0,by-1)*boardW+bx]||board[Math.min(boardH-1,by+1)*boardW+bx])contact++}return contact}

function firstMaskPosition(board,boardW,boardH,mask,scan){if(scan==='column'){for(let x=0;x<=boardW-mask.w;x++)for(let y=0;y<=boardH-mask.h;y++)if(maskFits(board,boardW,mask,x,y))return{x,y}}else for(let y=0;y<=boardH-mask.h;y++)for(let x=0;x<=boardW-mask.w;x++)if(maskFits(board,boardW,mask,x,y))return{x,y};return null}

function packContourPass(masks,target,sheet,scale,scan,seed){const boardW=Math.floor(sheet.w*scale),boardH=Math.floor(sheet.h*scale),board=new Uint8Array(boardW*boardH),placed=[];let usedRight=0,usedBottom=0;for(let i=0;i<target;i++){let best=null;for(let n=0;n<masks.length;n++){const mask=masks[(n+seed+i)%masks.length],position=firstMaskPosition(board,boardW,boardH,mask,scan);if(!position)continue;const right=Math.max(usedRight,position.x+mask.w),bottom=Math.max(usedBottom,position.y+mask.h),contact=maskContact(board,boardW,boardH,mask,position.x,position.y),score=right*bottom+bottom*boardW*.12+right*boardH*.04-contact*scale*3;if(!best||score<best.score)best={...position,mask,right,bottom,score}}if(!best)break;for(const[px,py]of best.mask.pixels)board[(best.y+py)*boardW+best.x+px]=1;usedRight=best.right;usedBottom=best.bottom;placed.push({x:best.x/scale+best.mask.pad,y:best.y/scale+best.mask.pad,w:best.mask.actualW,h:best.mask.actualH,angle:best.mask.angle,pdfMinX:best.mask.pdfMinX,pdfMinY:best.mask.pdfMinY,i})}return{items:placed,envelope:usedRight*usedBottom}}

function packContour(art,target,sheet,gap,allowRotation){const scale=contourScale(art,gap),masks=contourMasks(art,gap,allowRotation,scale),passes=[packContourPass(masks,target,sheet,scale,'row',0),packContourPass(masks,target,sheet,scale,'column',Math.max(1,Math.floor(masks.length/3)))];passes.sort((a,b)=>b.items.length-a.items.length||a.envelope-b.envelope);return passes[0].items}

self.onmessage=event=>{const{id,art,target,sheet,gap,allowRotation}=event.data;try{const items=packContour(art,target,sheet,gap,allowRotation);self.postMessage({id,items})}catch(error){self.postMessage({id,error:error instanceof Error?error.message:String(error)})}}
