// Phase 2A algorithms shared by the worker and Step & Repeat.
// Grid/staggered/brick placement calculations are unchanged. Honeycomb raster
// rows are refined against vector cut geometry before they can be used.
import { refineHoneycombRows } from './honeycomb-spacing.js';
export function contourScale(art,gap){const box=art.contour?.mmBox||[0,0,art.w,art.h],longest=Math.max(box[2],box[3]);if(longest<=90&&gap<=4)return 2;if(longest<=160)return 1.5;return 1}
export function makeMask(art,gap,angle=0,scale=1){const [bx,by,bw,bh]=art.contour.box,physical=art.contour.mmBox||[0,0,art.w,art.h],baseW=Math.max(1,Math.ceil(physical[2]*scale)),baseH=Math.max(1,Math.ceil(physical[3]*scale)),canvas=typeof OffscreenCanvas==='function'?new OffscreenCanvas(1,1):document.createElement('canvas');canvas.width=baseW;canvas.height=baseH;const ctx=canvas.getContext('2d');ctx.scale(baseW/bw,baseH/bh);ctx.translate(-bx,-by);ctx.fill(new Path2D(art.contour.d));const data=ctx.getImageData(0,0,baseW,baseH).data,source=[];for(let y=0;y<baseH;y++)for(let x=0;x<baseW;x++)if(data[(y*baseW+x)*4+3]>20)source.push([x+.5,y+.5]);if(!source.length)return null;const radians=angle*Math.PI/180,c=Math.cos(radians),s=Math.sin(radians),cx=baseW/2,cy=baseH/2,turned=[],pdfPoints=[];for(const[x,y]of source){turned.push([(x-cx)*c+(y-cy)*s,-(x-cx)*s+(y-cy)*c]);const px=physical[0]+x/baseW*physical[2],py=physical[1]+(baseH-y)/baseH*physical[3];pdfPoints.push([px*c-py*s,px*s+py*c])}const xs=turned.map(p=>p[0]),ys=turned.map(p=>p[1]),minX=Math.floor(Math.min(...xs)),minY=Math.floor(Math.min(...ys)),maxX=Math.ceil(Math.max(...xs)),maxY=Math.ceil(Math.max(...ys)),rawW=Math.max(1,maxX-minX),rawH=Math.max(1,maxY-minY),r=Math.max(0,Math.ceil(gap*scale/2)),w=rawW+r*2,h=rawH+r*2,map=new Uint8Array(w*h);for(const[pX,pY]of turned){const x=Math.floor(pX-minX)+r,y=Math.floor(pY-minY)+r;for(let dy=-r;dy<=r;dy++)for(let dx=-r;dx<=r;dx++)if(dx*dx+dy*dy<=r*r&&x+dx>=0&&x+dx<w&&y+dy>=0&&y+dy<h)map[(y+dy)*w+x+dx]=1}const pixels=[];for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(map[y*w+x])pixels.push([x,y]);return{w,h,pixels,angle,actualW:rawW/scale,actualH:rawH/scale,pad:r/scale,pdfMinX:Math.min(...pdfPoints.map(p=>p[0])),pdfMinY:Math.min(...pdfPoints.map(p=>p[1]))}}
export function contourMasks(art,gap,allowRotation,scale){const cache=new Map(),get=angle=>{const normalized=(angle+360)%360;if(!cache.has(normalized))cache.set(normalized,makeMask(art,gap,normalized,scale));return cache.get(normalized)},coarse=allowRotation?Array.from({length:24},(_,i)=>i*15):[0],coarseMasks=coarse.map(get).filter(Boolean);if(!allowRotation)return coarseMasks;const promising=[...coarseMasks].sort((a,b)=>a.w*a.h-b.w*b.h).slice(0,8),angles=new Set([0,90,180,270]);for(const mask of promising)for(const delta of[-5,-2,-1,0,1,2,5])angles.add((mask.angle+delta+360)%360);const ranked=[...angles].map(get).filter(Boolean).sort((a,b)=>a.w*a.h-b.w*b.h),zero=get(0);return[zero,...ranked.filter(mask=>mask.angle!==0).slice(0,7)]}
export function maskFits(board,boardW,mask,x,y){for(const[px,py]of mask.pixels)if(board[(y+py)*boardW+x+px])return false;return true}
export function erodeMask(mask){const map=new Uint8Array(mask.w*mask.h);for(const[x,y]of mask.pixels)map[y*mask.w+x]=1;const pixels=mask.pixels.filter(([x,y])=>x>0&&y>0&&x<mask.w-1&&y<mask.h-1&&map[y*mask.w+x-1]&&map[y*mask.w+x+1]&&map[(y-1)*mask.w+x]&&map[(y+1)*mask.w+x]);return{...mask,pixels}}
export function maskContact(board,boardW,boardH,mask,x,y){let contact=0,step=Math.max(1,Math.floor(mask.pixels.length/240));for(let i=0;i<mask.pixels.length;i+=step){const[px,py]=mask.pixels[i],bx=x+px,by=y+py;if(bx===0||by===0||bx===boardW-1||by===boardH-1||board[by*boardW+Math.max(0,bx-1)]||board[by*boardW+Math.min(boardW-1,bx+1)]||board[Math.max(0,by-1)*boardW+bx]||board[Math.min(boardH-1,by+1)*boardW+bx])contact++}return contact}
export function firstMaskPosition(board,boardW,boardH,mask,scan){if(scan==='column'){for(let x=0;x<=boardW-mask.w;x++)for(let y=0;y<=boardH-mask.h;y++)if(maskFits(board,boardW,mask,x,y))return{x,y}}else for(let y=0;y<=boardH-mask.h;y++)for(let x=0;x<=boardW-mask.w;x++)if(maskFits(board,boardW,mask,x,y))return{x,y};return null}
export function packContourPass(masks,target,sheet,scale,scan,seed){const boardW=Math.floor(sheet.w*scale),boardH=Math.floor(sheet.h*scale),board=new Uint8Array(boardW*boardH),placed=[];let usedRight=0,usedBottom=0;for(let i=0;i<target;i++){let best=null;for(let n=0;n<masks.length;n++){const mask=masks[(n+seed+i)%masks.length],position=firstMaskPosition(board,boardW,boardH,mask,scan);if(!position)continue;const right=Math.max(usedRight,position.x+mask.w),bottom=Math.max(usedBottom,position.y+mask.h),contact=maskContact(board,boardW,boardH,mask,position.x,position.y),score=right*bottom+bottom*boardW*.12+right*boardH*.04-contact*scale*3;if(!best||score<best.score)best={...position,mask,right,bottom,score}}if(!best)break;for(const[px,py]of best.mask.pixels)board[(best.y+py)*boardW+best.x+px]=1;usedRight=best.right;usedBottom=best.bottom;placed.push({x:best.x/scale+best.mask.pad,y:best.y/scale+best.mask.pad,w:best.mask.actualW,h:best.mask.actualH,angle:best.mask.angle,pdfMinX:best.mask.pdfMinX,pdfMinY:best.mask.pdfMinY,i})}return{items:placed,envelope:usedRight*usedBottom}}
export function packContour(art,target,sheet,gap,allowRotation){const scale=contourScale(art,gap),masks=contourMasks(art,gap,allowRotation,scale),passes=[packContourPass(masks,target,sheet,scale,'row',0),packContourPass(masks,target,sheet,scale,'column',Math.max(1,Math.floor(masks.length/3)))];passes.sort((a,b)=>b.items.length-a.items.length||a.envelope-b.envelope);return passes[0].items}
export function packRect(art,target,sheet,gap,rotation){let x=gap,y=gap,row=0,result=[];for(let i=0;i<target;i++){let w=art.w,h=art.h,rotated=false;if(rotation&&x+w>sheet.w-gap&&h<=sheet.w-x-gap){[w,h]=[h,w];rotated=true}if(x+w>sheet.w-gap){x=gap;y+=row+gap;row=0}if(y+h>sheet.h-gap)break;result.push({x,y,w,h,i,rotated,angle:rotated?90:0});x+=w+gap;row=Math.max(row,h)}return result}
export function repeatGeometry(art,angle=0){const[x,y,width,height]=art.contour?.mmBox||[0,0,art.w,art.h],normalized=(angle+360)%360,radians=normalized*Math.PI/180,c=Math.cos(radians),s=Math.sin(radians),corners=[[x,y],[x+width,y],[x,y+height],[x+width,y+height]].map(([px,py])=>[px*c-py*s,px*s+py*c]),xs=corners.map(point=>point[0]),ys=corners.map(point=>point[1]),turned=normalized===90||normalized===270;return{w:turned?height:width,h:turned?width:height,pdfMinX:Math.min(...xs),pdfMinY:Math.min(...ys),angle:normalized}}
export function packPattern(art,target,sheet,gap,pattern,angle=0){const{pdfMinX,pdfMinY,w,h,angle:normalized}=repeatGeometry(art,angle),xStep=w+gap,yStep=pattern==='honeycomb'?(h+gap)*Math.sqrt(3)/2:h+gap,result=[];let i=0;if(pattern==='brick'){let column=0;while(i<target){const x=column*xStep,offset=column%2*yStep/2;if(x+w>sheet.w)break;for(let y=offset;y+h<=sheet.h&&i<target;y+=yStep){result.push({x,y,w,h,i,angle:normalized,pdfMinX,pdfMinY});i++}column++}return result}let row=0;while(i<target){const offset=pattern==='grid'?0:row%2*xStep/2,y=row*yStep;if(y+h>sheet.h)break;for(let x=offset;x+w<=sheet.w&&i<target;x+=xStep){result.push({x,y,w,h,i,angle:normalized,pdfMinX,pdfMinY});i++}row++}return result}
export function packHoneycombRows(art,target,sheet,gap,angle=0){const{pdfMinX,pdfMinY,w,h,angle:normalized}=repeatGeometry(art,angle),scale=Math.max(4,contourScale(art,gap)),sourceMask=makeMask(art,gap,normalized,scale);if(!sourceMask)return packPattern(art,target,sheet,gap,'staggered',normalized);const eroded=erodeMask(sourceMask),mask=eroded.pixels.length?eroded:sourceMask,padding=Math.ceil(sourceMask.pad*scale),boardW=Math.ceil(sheet.w*scale)+padding*2,boardH=Math.ceil(sheet.h*scale)+padding*2,xStep=w+gap;const run=startPhase=>{const board=new Uint8Array(boardW*boardH),items=[];let row=0,previousY=-1,lastBottom=0;while(items.length<target){const offset=(row+startPhase)%2*xStep/2,xs=[];for(let x=offset;x+w<=sheet.w+.001&&items.length+xs.length<target;x+=xStep)xs.push(x);if(!xs.length)break;let foundY=-1;for(let y=Math.max(0,previousY+1);y/scale+h<=sheet.h+.001;y++){let fits=true;for(const x of xs){const px=Math.round(x*scale);if(px<0||px+mask.w>boardW||y+mask.h>boardH||!maskFits(board,boardW,mask,px,y)){fits=false;break}}if(fits){foundY=y;break}}if(foundY<0)break;for(const x of xs){const px=Math.round(x*scale);for(const[mx,my]of mask.pixels)board[(foundY+my)*boardW+px+mx]=1;items.push({x,y:foundY/scale,w,h,i:items.length,angle:normalized,pdfMinX,pdfMinY})}previousY=foundY;lastBottom=foundY/scale+h;row++}return{items,lastBottom}};const layouts=[run(0),run(1)].sort((a,b)=>b.items.length-a.items.length||a.lastBottom-b.lastBottom);return layouts[0].items}
export function validatedPatternPack(art,target,sheet,gap,pattern,angle=0){if(pattern==='honeycomb'&&art.contour)return refineHoneycombRows(packHoneycombRows(art,target,sheet,gap,angle),art,sheet,gap);return packPattern(art,target,sheet,gap,pattern,angle)}
